#if !canImport(ObjectiveC)
import XCTest

extension CompleteAssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompleteAssertionTests = [
        ("testComplete", testComplete),
        ("testNotComplete", testNotComplete),
    ]
}

extension ErrorAssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorAssertionTests = [
        ("testErrorEvent", testErrorEvent),
        ("testNotErrorEvent", testNotErrorEvent),
    ]
}

extension NextAssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NextAssertionTests = [
        ("testNextEventsHelpers", testNextEventsHelpers),
        ("testNotSentNext", testNotSentNext),
        ("testSentNextEvent", testSentNextEvent),
    ]
}

extension OperatorAssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OperatorAssertionTests = [
        ("testEmpty", testEmpty),
        ("testJust", testJust),
        ("testMatchFirstNext", testMatchFirstNext),
        ("testMatchFirstNextBehaviorRelay", testMatchFirstNextBehaviorRelay),
        ("testMatchFirstNextPublishRelay", testMatchFirstNextPublishRelay),
        ("testNever", testNever),
        ("testNeverPublishRelay", testNeverPublishRelay),
    ]
}

extension TestSchedulerExtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestSchedulerExtTests = [
        ("testRecordingAllEvents", testRecordingAllEvents),
        ("testRecordingAllEventsBehaviorRelay", testRecordingAllEventsBehaviorRelay),
        ("testRecordingAllEventsPublishRelay", testRecordingAllEventsPublishRelay),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CompleteAssertionTests.__allTests__CompleteAssertionTests),
        testCase(ErrorAssertionTests.__allTests__ErrorAssertionTests),
        testCase(NextAssertionTests.__allTests__NextAssertionTests),
        testCase(OperatorAssertionTests.__allTests__OperatorAssertionTests),
        testCase(TestSchedulerExtTests.__allTests__TestSchedulerExtTests),
    ]
}
#endif
